# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20151119_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='createddate',
            field=models.DateField(blank=True, db_column='createdDate', default=b'2015-12-12', null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='createddate',
            field=models.DateField(blank=True, db_column='createdDate', default=b'2015-12-12', null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='products',
            name='createddate',
            field=models.DateField(blank=True, db_column='createdDate', default=b'2015-12-12', verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
